language: java

jdk:
  - openjdk8
  
jobs:
  include:
    - stage: build
      script: "mvn clean verify"
    - stage: package
      script: "mvn clean package"
    - stage: deploy
      script: "mvn heroku-deploy"
stages:
  - name: build
    if: (branch = develop)
  - name: package
    if: (branch = master) AND (NOT (type IN (push, pull_request)))
  - name: deploy
    if: (branch = master) AND (NOT (type IN (push, pull_request)))
