language: java
jdk:
  - openjdk8
install: true
script: if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "No Deploy" && mvn clean verify; else echo "Deploying.." && mvn clean package && mvn heroku:deploy; fi
