language: java
jdk:
  - openjdk8
install: true
jobs:
  include:
    - if: type != pull_request
      script: mvn clean package && mvn heroku:deploy
    - if: type = pull_request
      script: mvn clean verify
