language: java
jdk:
  - openjdk8
install: true
jobs:
  include:
    - if: branch = master
      script: mvn clean package && mvn heroku:deploy
    - if: branch = develop
      script: mvn clean verify
